# Standard GitHub Actions workflow file. No Docker Container.

name: DataTribe's Weekly Post Convertor
on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install md-to-pdf
        run: npm install -g md-to-pdf

      - name: Convert Markdown to PDF
        run: |
          shopt -s globstar  # Enable recursive globbing (for Bash)
          for md_file in **/*.md; do
            [ -f "$md_file" ] || continue  # Skip if no files found
            pdf_file="${md_file%.md}.pdf"
            
            echo "Converting files..."
            md-to-pdf "$md_file" --config-file ./config.js
          done

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: "./**/*.pdf"