# Ver1 Github Action Workflow File. 

name: DataTribe Weekly Post Generator

on:
  push:
    branches:
      - main

jobs:
  data-tribe-weekly-post-generator:
    runs-on: ubuntu-latest 

    container: debian:bookworm-slim 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends pandoc wkhtmltopdf
      - name: Find and Convert Markdown to HTML with Template
        run: |
            ROOT_DIR=$(pwd)
            find . -type f -name "*.md" | while read -r md_file; do
              folder=$(dirname "$md_file")
              filename=$(basename "$md_file" .md)
              html_file="${folder}/${filename}.html"
              pdf_file="${folder}/${filename}.pdf"
        
              echo "Processing $md_file -> $html_file -> $pdf_file"
        
              pandoc "$md_file" -o "$html_file" --template="$ROOT_DIR/template.html" --css="$ROOT_DIR/style.css" --metadata title="$filename"
        
              wkhtmltopdf --enable-local-file-access "$html_file" "$pdf_file"
            done
                    
      - name: Upload PDFs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: markdown-pdfs
          path: "**/*.pdf"