name: DataTribe Weekly Post Generator

on:
  push:
    branches:
      - main

jobs:
  dataribe-weekly-post-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Convert Markdown to HTML with Template
        run: |
          pandoc README.md -o final.html --template=template.html --css=style.css --metadata title="..."

      - name: Convert HTML to PDF
        run: |
          wkhtmltopdf --enable-local-file-access final.html output.pdf

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-pdf
          path: output.pdf